### ISSUE TITLE
Feature request: checkboxes and comboboxes

### ISSUE THREAD

**Issue by Dim3nsioneer** [nallath/PostProcessingPlugin#1]
Hi Nallath

If you add the possibility to have checkboxes and comboboxes as input fields (cf. legacy Cura) it would be possible to implement e.g. TweakAtZ 4.0.x for the new Cura. Without it only a TweakAtZ 3.x would be possible.

thx,
Dim3nsioneer

**Comment by nallath** [comment]
This is already possible. The plugin uses the same types for settings as Cura.

**Comment by Dim3nsioneer** [comment]
Yep, you're right... tried 'enum' and 'boolean'...

**Comment by Dim3nsioneer** [comment]
bonus question: "active_if" property is not working here, isn't it?

**Comment by nallath** [comment]
I believe it should. But the active_if pretty much only governs the visibility of an item.
