### ISSUE TITLE
settings do not show in cura-git

### ISSUE THREAD

**Issue by hmalzahn** [nallath/PostProcessingPlugin#10]
I'm not sure if the plugin is intended to work in git builds of cura, or only in regular releases. If that's the case, a hint would be great.

If it is supposed to work, at least in my setup it doesn't: I'm using the AUR (ArchLinux) build of the cura git state (https://github.com/Ultimaker/Cura.git), and while the plugin shows in the menu and I can add scripts to the list, I cannot set (or even see) any values. See the attached screenshot and log.

![screenshot_20160628_153714](https://cloud.githubusercontent.com/assets/15311866/16417706/279546ea-3d47-11e6-82c9-30b9ad3071dd.png)

[cura_log.txt](https://github.com/nallath/PostProcessingPlugin/files/337138/cura_log.txt)

**Comment by nallath** [comment]
At the moment the post processing is broken. I havent gotten to changing it based on the rework we just did.
