### ISSUE TITLE
PauseAtHeight: Printing with multiple material types

### ISSUE THREAD

**Issue by peteruithoven** [nallath/PostProcessingPlugin#19]
I was trying to print with multiple types of materials that require different temperatures, on a Ultimaker 2, but I was having big problems when using the PauseAtHeight script as it is.

The problem seems to be that the current change material system of the Ultimaker 2 only asks which material type is inserted after its completely done, which means there is no step where it extrudes the new material at it's proper temperature.
I'm thinking now that this caused that, after the pause, it took another two layers before the material to start flowing properly, which meant that the parts fall apart.

As a short term solution I was thinking of adding a extrusion option to the PauseAtHeight script. This so that it can extrude after having the right material type selected and get a proper material flow going.
One downside will be that there extruded material might end up on the print.
I'll try doing a PR soon, but in the meantime I'm curious about opinions.

**Comment by Ghostkeeper** [comment]
You could move to coordinates 0,0 or something before priming, but you'd need to find and parse the previous move command to find the location to move back to, in order to properly resume the print.

**Comment by peteruithoven** [comment]
I might not fully understand the script but wouldn't setting the `Head park X` and `Head park Y` to 0 give the same result?

**Comment by Ghostkeeper** [comment]
Ah, yes, that should indeed be fine. But that would allow the user to make sure it doesn't extrude right on top of the print, right?

Useful addition to the pause script, I think. I hope it wouldn't go grinding the material when it's too cold to print.

**Comment by peteruithoven** [comment]
Ah, I get the misunderstanding, with:

> One downside will be that there extruded material might end up on the print.

I meant that the filament might be dragged along while the nozzle moves back to the print. I think this is one of the reasons we print skirts. 

My solution doesn't always seem to work (it doesn't always seem to extrude after the pause), I'll try to create a very small test print to quickly debug this.

**Comment by peteruithoven** [comment]
More recent Ultimaker2 firmware asks the material type before you insert it, but ~~there still seems to be a small bug which makes~~ it retracts after changing the material, while it doesn't extrude the same amount when the print is continued: https://github.com/Ultimaker/Ultimaker2Marlin/issues/117. It

**Comment by peteruithoven** [comment]
Changing all the extrusion commands after the pause doesn't seem scalable, if anyone has an idea on how I could add extra extrusion without this that would be very welcome. 
Ideally I could be reset the extrude amount the firmware thinks it's at, but I don't think that's possible.

**Comment by Ghostkeeper** [comment]
As a patch, perhaps we could add a checkbox to the Pause at Height script to tick when you intend to pause for a material change, which then makes sure (using additional retracts/primes) that the material gets put in the correct position after the material change.

**Comment by peteruithoven** [comment]
That sounds like a good solution, interface wise, but I'm not sure how to do an extra extrusion without having to change all the extrusion related gcode that comes after it.

**Comment by Ghostkeeper** [comment]
I think to remember it's possible via some trickery with the G92 command.

**Comment by peteruithoven** [comment]
@Ghostkeeper thanks for the tip, together with@sjoerdtimmer (themba@randomdata.nl) I figured out how we could use G92, see: https://github.com/nallath/PostProcessingPlugin/pull/20/commits/ca2faf2d9bfa01445f1b33f24d6052bcb07b55f2
Except for the https://github.com/nallath/PostProcessingPlugin/issues/25 issue this usecase is now handled by the plugin.

**Comment by Ghostkeeper** [comment]
Exactly what I had in mind!
