### ISSUE TITLE
Arbitrary order of the entry boxes?

### ISSUE THREAD

**Issue by Dim3nsioneer** [nallath/PostProcessingPlugin#2]
After I realised the PostProcessPlugin does not keep the order as specified in 'getSettingData' for display, I restarted Cura. After restart I got a different order, then another one after next Cura restart, ...
Could you please remove that random generator? ;-)

**Comment by nallath** [comment]
That is weird. It should just list the items in the order they are provided by the json. I'll have a look.

**Comment by nallath** [comment]
It now sorts them by name.

**Comment by Dim3nsioneer** [comment]
And by name you mean by 'label'... that's actually a bit suboptimal for larger plugins where one should have the freedom to decide which field comes first. Would it be possible to sort by key? E.g. in your example script, 'Test' now comes before 'zomg'. What if it would be sorted in a way that 'derp' comes before 'test'? This is still a bit unpractical but at least one could work with 'A_first', 'B_second', 'C_third' etc. without being noticed by the user (as it would be the case with the same trick at the labels).

**Comment by nallath** [comment]
And done :)

**Comment by Dim3nsioneer** [comment]
Great, thanks! Consider me now working on the TweakAtZ 5.0 postprocessing script... ;-)

**Comment by nallath** [comment]
Yay :D

**Comment by Dim3nsioneer** [comment]
Is an implementation of the Postprocessing plugin into the new Cura planned? I could imagine it would need some corporate identity repaintings...

**Comment by nallath** [comment]
Yeah it is. We just haven't gotten to making a design yet.
