### ISSUE TITLE
Clarify PauseAtHeight retraction

### ISSUE THREAD

**Issue by peteruithoven** [nallath/PostProcessingPlugin#23]
So the Ultimaker2 retracts a bit of material after it changed material. This can currently cause a problem when changing materials during a pause. From @TinkerGnome I understand that to compensate the retraction setting needs to be the same as the end-of-print retraction (20mm by default). See: https://github.com/Ultimaker/Ultimaker2Marlin/issues/117#issuecomment-253014761

Honestly I don't understand it, since the 4 extrudes in the PauseAtHeight script seem to cancel each other out in the end. Can someone confirm that this works? 

Shouldn't 20mm be the default Retraction? 
Should I do a PR to explain this in the Retraction setting description?

**Comment by peteruithoven** [comment]
Also, would this setting needs to be converted to cubic mm when it's added to UltiGCode gcode? 
See: https://ultimaker.com/en/community/22204-um2-pause-at-height-and-then-change-filament-from-screen#reply-154003

**Comment by nallath** [comment]
In the pause, all extrudes should cancel each other out. Thats the entire point of it. 

Basicly what you do is: 
1. Retract (To prevent oozing)
2. Pause
3. Extrude (so we can continue printing)

I do agree that 20mm should be the default retraction. 

In case of Ulti-gcode, it should indeed be re-calculated, as the setting states that it's in mm (and not cubic mm)

**Comment by peteruithoven** [comment]
I created a PR for the default retraction and opened an issue about re-calculting the retraction amount for Ulti-gcode. 
I'm closing this issue, with Nallath's input I don't believe that the Retraction setting can be used to compensate for the post material change retraction.
