### ISSUE TITLE
'active_if' lets PostProcessingPlugin hang

### ISSUE THREAD

**Issue by Dim3nsioneer** [nallath/PostProcessingPlugin#3]
When an 'active_if' element is used within the settings the PostProcessingPlugin dialog doesn't open. It's the same behavior as for any syntax error within the script. Unfortunately Cura/PostProcessingPlugin is extremely non-verbose... nothing in Cura.log.

**Comment by nallath** [comment]
Good point, didn't think about adding logging to the plugin. Will add that soon.

**Comment by nallath** [comment]
Fixed the issue and added a bit more logging. Let me know if you need anything else.

**Comment by Dim3nsioneer** [comment]
Thanks. Let's see if something else is needed on the way...

**Comment by Dim3nsioneer** [comment]
Another bonus question: Is it possible to give a list to the active_if setting? If I want e.g. an entry to be active if another entry has option1, option2 or option4 selected but not for option3... ?

**Comment by nallath** [comment]
I don't believe that's possible in the current system. I've copied the system uranium / Cura uses. Might be that this will be posible in the future. Might be that @awhiemstra knows

**Comment by awhiemstra** [comment]
I have replaced the active_if with an enabled property in the per_object_settings branch. That property returns a function and works the same way the inherit function works. With that it should be possible to use a list of values.

**Comment by Dim3nsioneer** [comment]
@awhiemstra : Can you please refer to a corresponding commit? Does it mean 'active_if' should not be used anymore?
