### ISSUE TITLE
Tweaking a value on Layer 0 doesn't work - Tweaks Layer 1 instead

### ISSUE THREAD

**Issue by cinderblock** [nallath/PostProcessingPlugin#34]
If `Tweak Layer` is set to `0`, the tweaks are added on Layer 0 (where expected) **and** on layer 1 (not expected). It also resets the tweaked values right after they are set on layer 0, effectively moving the tweak to layer 1.

In this example, I used `Single Layer` `Behavior`. The same problem happens if `Keep Value` is used instead.

## Steps to reproduce
1. Set `Layer Number` to `0`
2. Tweak a value

## Expected Results

```
; ...
;LAYER:0
;...
;TweakAtZ V5.1: executed at Layer 0
M117 Printing... tw@L   0
M104 S250.000000 T0
;...
;LAYER:1
;...
;TweakAtZ V5.1: reset on Layer 1
M104 S240.000000 T0
```

## Actual Results
```
; ...
;LAYER:0
;...
;TweakAtZ V5.1: executed at Layer 0
M117 Printing... tw@L   0
M104 S250.000000 T0
;TweakAtZ V5.1: reset below Layer 0
M104 S240.000000 T0
;LAYER:1
;...
;TweakAtZ V5.1: executed at Layer 1
M117 Printing... tw@L   1
M104 S250.000000 T0
;...
;LAYER:2
;...
;TweakAtZ V5.1: reset on Layer 2
M104 S240.000000 T0
```

**Comment by Ghostkeeper** [comment]
Also reported in the Cura repository (though I think this is indeed a better place for it): https://github.com/Ultimaker/Cura/issues/1344
