### ISSUE TITLE
Gcode does not re-postprocess after changing postprocessing script setting values

### ISSUE THREAD

**Issue by d235j** [nallath/PostProcessingPlugin#52]
Due to the logic at https://github.com/nallath/PostProcessingPlugin/blob/master/PostProcessingPlugin.py#L59, it is assumed that once gcode is postprocessed it won't change. However, if gcode is in the buffer and changes to the postprocessing script setting values are made, those changes will not reflect in the output.

This was previously reported here: https://github.com/Ultimaker/Cura/issues/1856

My suggestion is to just remove that logic that looks for ```;POSTPROCESSED``` in the gcode, as it doesn't seem straightforward to tell if the settings were changed — but perhaps there is a way to do this.

**Comment by nallath** [comment]
The execute will only be called once the write-started is called. This is only done when the g-code is actually sent to the printer or saved to file.

That bit of code is just there to prevent g-code that was loaded (and pre-processed) to be pre-processed again.

**Comment by d235j** [comment]
Hmm, doesn't seem to reproduce anymore for me. Might have been fixed at some point by causing the proper trigger to re-slice on parameter changes to be generated.
