### ISSUE TITLE
Allow printer definition to specify postprocessing script with parameters to be automatically run on export

### ISSUE THREAD

**Issue by d235j** [nallath/PostProcessingPlugin#53]
I've been working on Makerbot Replicator 2 compatibility and one of the problems that I've run into is that these printers require the slicing software to insert percentage commands for the printer to show progress.
While this would probably be best handled in the slicer, one way of doing so is with a postprocessing script. Unfortunately though, the user experience of having to manually add a postprocessing script is not all that straightforward and has to be done each time slicing takes place.
It would be great if there was some automated way to do this.

**Comment by nallath** [comment]
I think it would be better to write a plugin that does this but only if a Makerbot Replicator is active.

This plugin is maintained by Ultimaker, so i don't think a feature to make the replicator work will be added by them.

**Comment by d235j** [comment]
That's fair; I believe I have a better solution anyway.
