### ISSUE TITLE
TweakAtZ plugin not working in Cura 2.1

### ISSUE THREAD

**Issue by whypurplishblue** [nallath/PostProcessingPlugin#9]
Not sure if this is the place to log the issue. 

When using the TweakAtZ 5.0 plugin, the generated gcode doesn't output the configured changes. 

![2016-05-15 10_49_46-text pdf - foxit reader](https://cloud.githubusercontent.com/assets/2075607/15271758/77683418-1a8b-11e6-9910-36ce2b6b330b.png)

Notice an error in the cura log.

**Script raised the following exception 'bedTemp'**

Attached cura log and screenshot of tweakAtZ Settings.
[tweakAtZerror.txt](https://github.com/nallath/PostProcessingPlugin/files/264812/tweakAtZerror.txt)

**Comment by Dim3nsioneer** [comment]
Strange. Can't reproduce that. On my Cura 2.1 installation it even works with an UMO without heated bed. What printer do you have defined in Cura 2.1?

Btw: That's exactly the place to drop issues on postprocessing scripts...

**Comment by nallath** [comment]
That's reaaly weird. I'm guessing it has something to do with your modified printer though. All printers I tested it on worked just fine.

**Comment by Dim3nsioneer** [comment]
Fixed: https://github.com/nallath/PostProcessingPlugin/commit/65f57a3a74c4ae82c9d5448ab1a14cf446557be3
